- name: Check for ODF StorageClass
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: ocs-storagecluster-cephfs
  register: odf_storage_class
  until: odf_storage_class is not failed

# have to manually create the PVC when using LVMS
# this is because the image registry attempts to create a PVC as ReadWriteMany, which LVMS doesn't support
- name: Create PVC for Image Registry
  when: odf_storage_class.resources | length | int == 0
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: registry-storage-pvc
        namespace: openshift-image-registry
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Get current Image Registry settings
  kubernetes.core.k8s_info:
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
    name: cluster
  register: image_registry
  until: image_registry is not failed

- name: Configure Image Registry
  kubernetes.core.k8s:
    template: ImageRegistry.yaml.j2
    state: present
    wait: true
    wait_timeout: 1200
    wait_condition:
      type: Available
      status: "True"
  register: k8s_result
  until: k8s_result is not failed
