- name: Get cluster version
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_sleep: 10
    wait_timeout: 1200
  register: cluster_version

- name: Setup PAO
  when: >
    (edgeCluster.performanceProfileSpec is defined) and
    (cluster_version.resources[0].status.desired.version is version('4.11.0', 'lt', version_type='semver'))
  block:
    - name: Install PAO operator
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../common/roles/install_operator"
      vars:
        operator_name: performance-addon-operator
        operator_namespace: openshift-performance-addon-operator
        all_namespaces: true

    - name: Setup PerformanceProfile
      loop: "{{ edgeCluster.performanceProfileSpec | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      kubernetes.core.k8s:
        template: ../edge_install/templates/PerformanceProfile.yaml.j2
        apply: true
        state: present
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 1200
      register: setup_pao
