- name: Label nodes
  loop: "{{ nodes.resources }}"
  kubernetes.core.k8s:
    definition:
      api_version: v1
      kind: Node
      metadata:
        name: "{{ item.metadata.name }}"
        labels:
          cluster.ocs.openshift.io/openshift-storage: ""
    state: present

- name: Setup LSO
  ansible.builtin.include_tasks:
    file: storage_lso.yaml

- name: Install ODF operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    operator_name: ocs-operator
    operator_namespace: openshift-storage

- name: Get device count
  kubernetes.core.k8s_info:
    api_version: local.storage.openshift.io/v1alpha1
    kind: LocalVolumeSet
    name: local-storage
  register: local_storage

- name: Create StorageCluster
  kubernetes.core.k8s:
    template: StorageCluster.yaml.j2
    state: present

- name: Wait for StorageClass
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: ocs-storagecluster-cephfs
  register: odf_storage_class
  until: odf_storage_class.resources | length | int == 1
  retries: 60
  delay: 10

- name: Set default storage
  loop: "{{ odf_storage_class.resources }}"
  ansible.builtin.include_tasks: set_storage.yaml
