- name: Install ODF LVM Subscription
  kubernetes.core.k8s:
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: odf-lvm-operator
        namespace: openshift-storage
      spec:
        installPlanApproval: Automatic
        name: odf-lvm-operator
        source: "{{ odf_operator_source }}"
        sourceNamespace: openshift-marketplace
    state: present
  register: create_sub

- name: Pause for 15 seconds to let subscription settle # noqa no-handler
  when: create_sub.changed
  ansible.builtin.pause:
    seconds: 15

- name: Wait for operator to be deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: odf-lvm-operator
    namespace: openshift-storage
  register: subscription
  until: subscription.resources[0]["status"]["state"] == "AtLatestKnown"
  retries: 20
  delay: 10

- name: Pause for 15 seconds to let CSV settle # noqa no-handler
  when: create_sub.changed
  ansible.builtin.pause:
    seconds: 15

- name: Wait for CSV to be deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ subscription.resources[0]['status']['installedCSV'] }}"
    namespace: openshift-storage
  register: csv
  until: csv.resources[0]["status"]["phase"] == "Succeeded"
  retries: 20
  delay: 10

- name: Install StorageClass
  block:
    - name: Install ODF LVMCluster
      kubernetes.core.k8s:
        definition:
          apiVersion: lvm.topolvm.io/v1alpha1
          kind: LVMCluster
          metadata:
            name: odf-lvmcluster
            namespace: openshift-storage
          spec:
            storage:
              deviceClasses:
                - name: vg1
                  thinPoolConfig:
                    name: thin-pool-1
                    sizePercent: 90
                    overprovisionRatio: 10
        state: present

    - name: Wait for LVMCluster to be deployed
      kubernetes.core.k8s_info:
        api_version: lvm.topolvm.io/v1alpha1
        kind: LVMCluster
        name: odf-lvmcluster
        namespace: openshift-storage
      register: lvmcluster
      until: lvmcluster.resources[0]["status"]["ready"] == true
      retries: 20
      delay: 10
  rescue:
    - name: Remove StorageClass
      kubernetes.core.k8s:
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: odf-lvm-vg1
        state: absent
