- name: Install LVM operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    operator_name: odf-lvm-operator
    operator_namespace: openshift-storage

- name: Install ODF LVMCluster
  kubernetes.core.k8s:
    definition:
      apiVersion: lvm.topolvm.io/v1alpha1
      kind: LVMCluster
      metadata:
        name: odf-lvmcluster
        namespace: openshift-storage
      spec:
        storage:
          deviceClasses:
            - name: vg1
              thinPoolConfig:
                name: thin-pool-1
                sizePercent: 90
                overprovisionRatio: 10
    state: present

- name: Wait for StorageClass
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: odf-lvm-vg1
  register: lvm_storage_class
  until: lvm_storage_class.resources | length | int == 1
  retries: 60
  delay: 10

- name: Set default storage
  loop: "{{ lvm_storage_class.resources }}"
  ansible.builtin.include_tasks: set_storage.yaml
