- name: Install ODF Subscription
  kubernetes.core.k8s:
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ item }}"
        namespace: openshift-storage
      spec:
        installPlanApproval: Automatic
        name: "{{ item }}"
        source: "{{ odf_operator_source }}"
        sourceNamespace: openshift-marketplace
    state: present
  register: create_sub

- name: Pause for 15 seconds to let subscription settle # noqa no-handler
  when: create_sub.changed
  ansible.builtin.pause:
    seconds: 15

- name: Wait for operator to be deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ item }}"
    namespace: openshift-storage
  register: subscription
  until: subscription.resources[0]["status"]["state"] == "AtLatestKnown"
  retries: 20
  delay: 10

- name: Pause for 15 seconds to let CSV settle # noqa no-handler
  when: create_sub.changed
  ansible.builtin.pause:
    seconds: 15

- name: Wait for CSV to be deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ subscription.resources[0]['status']['installedCSV'] }}"
    namespace: openshift-storage
  register: csv
  until: csv.resources[0]["status"]["phase"] == "Succeeded"
  retries: 20
  delay: 10
