os_images:
  - openshiftVersion: "4.18"
    version: "4.18.30"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.18/4.18.30/rhcos-4.18.30-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.20"
    version: "4.20.13"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/4.20.13/rhcos-4.20.13-x86_64-live-iso.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.22"
    version: "4.22.0"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.22/4.22.0/rhcos-4.22.0-x86_64-live-iso.x86_64.iso"
    cpuArchitecture: "x86_64"
asc_db_size: 10Gi
asc_fs_size: 50Gi
asc_im_size: 50Gi
acm: false
