- name: Create temporary file for pull secret
  ansible.builtin.tempfile:
    state: file
  register: temp_pull_secret

- name: Copy pull secret to file
  ansible.builtin.copy:
    content: "{{ pullSecret }}"
    dest: "{{ temp_pull_secret.path }}"
    mode: "0600"

- name: Get Cluster Version # noqa no-changed-when
  ansible.builtin.command: oc adm release info -a {{ temp_pull_secret.path }} {{ edgeCluster.clusterImageSet }} -o json
  register: release_info_raw

- name: Remove pull secret
  ansible.builtin.file:
    path: "{{ temp_pull_secret.path }}"
    state: absent

- name: Parse cluster version
  ansible.builtin.set_fact:
    version_array: "{{ (release_info_raw.stdout | from_json).metadata.version | split('.') }}"

- name: Checkout ZTP repo
  ansible.builtin.git:
    repo: "https://github.com/openshift-kni/cnf-features-deploy.git"
    dest: "{{ playbook_dir }}/cnf-features-deploy"
    version: "release-{{ version_array.0 }}.{{ version_array.1 }}"

- name: Set DU Manifest list
  ansible.builtin.set_fact:
    du_manifests: "{{ lookup('ansible.builtin.fileglob', playbook_dir + '/cnf-features-deploy/ztp/source-crs/extra-manifest/*.yaml', wantlist=True) | sort }}"
