- name: Create Namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ metadata.name }}"
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Create image pull secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: "{{ pullSecret | b64encode }}"
      metadata:
        name: assisted-deployment-pull-secret
        namespace: "{{ metadata.name }}"
      type: kubernetes.io/dockerconfigjson
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Setup host networking
  when: nmstate_host.networkConfig is defined
  loop: "{{ platform.baremetal.hosts }}"
  loop_control:
    label: "{{ nmstate_host.name }}"
    loop_var: nmstate_host
  ansible.builtin.include_tasks: setup_host_networking.yaml

- name: Setup InfraEnv and BMH
  ansible.builtin.include_tasks: setup_bmh.yaml

- name: Create SSH key secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ metadata.name }}-sshkey"
        namespace: "{{ metadata.name }}"
      data:
        id_rsa.pub: "{{ sshKey | b64encode }}"
      type: Opaque
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Create CAPI Role
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: capi-provider-role
        namespace: "{{ metadata.name }}"
      rules:
        - apiGroups:
            - agent-install.openshift.io
          resources:
            - agents
          verbs:
            - "*"
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Create IPAddressPool for API
  kubernetes.core.k8s:
    template: IPAddressPool.yaml.j2
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed
  vars:
    pool_type: "{{ metadata.name }}-api"
    addresses: "{{ platform.baremetal.apiVIPs | default([platform.baremetal.apiVIP]) }}"

- name: Create L2Advertisement
  kubernetes.core.k8s:
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: "{{ metadata.name }}-api-adv"
        namespace: metallb-system
      spec:
        ipAddressPools:
          - "{{ metadata.name }}-api-address-pool"
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Get route domain
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: ingress
  until: ingress is not failed

- name: Create HostedCluster
  kubernetes.core.k8s:
    template: HostedCluster.yaml.j2
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Count workers
  loop: "{{ compute }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.set_fact:
    worker_count: "{{ (worker_count | int) + item.replicas }}"

- name: Wait for Agents to come online
  kubernetes.core.k8s_info:
    api_version: agent-install.openshift.io/v1beta1
    kind: Agent
    namespace: "{{ metadata.name }}"
  register: agents
  until: (agents.resources | length | int) == (worker_count | int)
  retries: 60
  delay: 10

- name: Create NodePool
  kubernetes.core.k8s:
    template: NodePool.yaml.j2
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed

- name: Wait for API Server to be deployed
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: kube-apiserver
    namespace: "{{ metadata.name }}-{{ metadata.name }}"
  register: api_server
  until: api_server.resources | length | int == 1
  retries: 60
  delay: 10

- name: Patch API Server
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: kube-apiserver
        namespace: "{{ metadata.name }}-{{ metadata.name }}"
        annotations:
          metallb.universe.tf/address-pool: "{{ metadata.name }}-api-address-pool"
    state: present
  register: k8s_result
  until: k8s_result is not failed
