- name: Add FIPS to config
  when: fips is defined
  ansible.builtin.set_fact:
    install_overrides: "{{ install_overrides | combine({'fips': fips}, recursive=true) }}"

- name: Add capabilities to config
  when: capabilities is defined
  ansible.builtin.set_fact:
    install_overrides: "{{ install_overrides | combine({'capabilities': capabilities}, recursive=true) }}"

- name: Add imageDigestSources to config
  when: imageDigestSources is defined
  ansible.builtin.set_fact:
    install_overrides: "{{ install_overrides | combine({'imageDigestSources': imageDigestSources}, recursive=true) }}"

- name: Add additionalTrustBundle to config
  when: additionalTrustBundle is defined
  ansible.builtin.set_fact:
    install_overrides: "{{ install_overrides | combine({'additionalTrustBundle': additionalTrustBundle}, recursive=true) }}"

- name: Add cpuPartitioningMode to config
  when: cpuPartitioningMode is defined
  ansible.builtin.set_fact:
    install_overrides: "{{ install_overrides | combine({'cpuPartitioningMode': cpuPartitioningMode}, recursive=true) }}"
