- name: Standard cluster install
  when: ((edgeCluster.hypershift is defined) and (not edgeCluster.hypershift)) or (edgeCluster.hypershift is not defined)
  ansible.builtin.include_tasks: standard.yaml

- name: Hypershift install
  when: (edgeCluster.hypershift is defined) and (edgeCluster.hypershift)
  ansible.builtin.include_tasks: hypershift.yaml
