- name: Install edge cluster
  block:
    - name: Create Namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ metadata.name }}"
        apply: true
        state: present
      register: k8s_result
      until: k8s_result is not failed

    - name: Create image pull secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          data:
            .dockerconfigjson: "{{ pullSecret | b64encode }}"
          metadata:
            name: assisted-deployment-pull-secret
            namespace: "{{ metadata.name }}"
          type: kubernetes.io/dockerconfigjson
        apply: true
        state: present
      register: k8s_result
      until: k8s_result is not failed

    - name: Enable HyperShift
      when:
        - edgeCluster.hypershift is defined
        - edgeCluster.hypershift.enabled
      ansible.builtin.set_fact:
        hypershift: true

    # these manifests are applied early in the install process, often they are MachineConfigs, applying them early helps avoid extra reboots
    - name: Create user-defined manifest config maps
      when: edgeCluster.installManifestsFolder is defined
      loop: "{{ lookup('ansible.builtin.fileglob', lookup('ansible.builtin.vars', 'install_manifests_folder') + '/*', wantlist=True) | sort }}"
      loop_control:
        index_var: idx
        label: "{{ item }}"
      kubernetes.core.k8s:
        template: ConfigMap.yaml.j2
        apply: true
        state: present
      vars:
        # this var is copied in like this because ansible.builtin.vars doesn't support dicts
        install_manifests_folder: "{{ edgeCluster.installManifestsFolder }}"
      register: k8s_result
      until: k8s_result is not failed

    - name: Count workers
      loop: "{{ compute }}"
      loop_control:
        label: "{{ item.name }}"
      ansible.builtin.set_fact:
        worker_count: "{{ (worker_count | int) + item.replicas }}"

    - name: Setup workload partitioning
      when: edgeCluster.reservedCpuSet is defined
      ansible.builtin.include_tasks: workload_partitioning.yaml

    - name: Standard cluster install
      when: not hypershift
      ansible.builtin.include_tasks: standard.yaml

    - name: HyperShift install
      when: hypershift
      ansible.builtin.include_tasks: hypershift.yaml
  rescue:
    - name: Delete ClusterImageSet
      kubernetes.core.k8s:
        definition:
          apiVersion: hive.openshift.io/v1
          kind: ClusterImageSet
          metadata:
            name: "{{ metadata.name }}"
        state: absent
        wait: true
        wait_timeout: 600

    - name: Delete BareMetalHosts
      loop: "{{ platform.baremetal.hosts }}"
      loop_control:
        label: "{{ item.name }}"
      kubernetes.core.k8s:
        template: BareMetalHost.yaml.j2
        state: absent
        wait: true
        wait_timeout: 600

    - name: Delete Namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ metadata.name }}"
        state: absent
        wait: true
        wait_timeout: 600

    - name: End playbook
      ansible.builtin.meta: end_play
