- name: Create NMStateConfig
  kubernetes.core.k8s:
    template: NMStateConfig.yaml.j2
    apply: true
    state: present

- name: Configure relocatable networking
  when: edgeCluster.relocatable is defined
  block:
    - name: Get relocatable interface index
      loop: "{{ nmstate_host.networkConfig.interfaces }}"
      loop_control:
        index_var: interface_index
      when: item.name == edgeCluster.relocatable
      ansible.builtin.set_fact:
        relocatableInterface: "{{ interface_index }}"

    - name: Patch NMStateConfig with relocatable IP
      kubernetes.core.k8s_json_patch:
        api_version: agent-install.openshift.io/v1beta1
        kind: NMStateConfig
        name: "{{ nmstate_host.name }}"
        namespace: "{{ metadata.name }}"
        patch:
          - op: add
            path: /spec/config/interfaces/{{ relocatableInterface | int }}/ipv4/address/-
            value:
              { "ip": "192.168.7.{{ (idx + 2) | int }}", "prefix-length": 24 }
