- name: Create relocatable IPv4 machineNetwork
  when: cluster_ipv4 is defined
  ansible.builtin.set_fact:
    relocatable_machine_network: "{{ [{'cidr': '192.168.7.0/24'}] }}"

- name: Create relocatable IPv6 machineNetwork
  when: cluster_ipv6 is defined
  ansible.builtin.set_fact:
    relocatable_machine_network: "{{ relocatable_machine_network | default([]) + [{'cidr': 'fd04::/64'}] }}"

- name: Set machineNetwork for relocatable cluster
  ansible.builtin.set_fact:
    relocatable_networking: "{{ networking | combine(new_network, recursive=true) }}"
  vars:
    new_network:
      machineNetwork: "{{ relocatable_machine_network }}"
