- name: Create config files for workload partitioning
  ansible.builtin.set_fact:
    workload_partitioning: |
      [crio.runtime.workloads.management]
      activation_annotation = "target.workload.openshift.io/management"
      annotation_prefix = "resources.workload.openshift.io"
      resources = { "cpushares" = 0, "cpuset" = "{{ edgeCluster.reservedCpuSet }}" }
    openshift_workload_pinning: |
      {
        "management": {
          "cpuset": "{{ edgeCluster.reservedCpuSet }}"
        }
      }

- name: Create workload partitioning config map
  kubernetes.core.k8s:
    template: WorkloadPartitioning.yaml.j2
    apply: true
    state: present
  register: k8s_result
  until: k8s_result is not failed
