- name: Check for HyperShift
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: hostedclusters.hypershift.openshift.io
  register: hostedclusters
  until: hostedclusters is not failed

- name: Set up HyperShift
  when: hostedclusters.resources | length | int == 0
  block:
    - name: Manage local-cluster
      kubernetes.core.k8s:
        definition:
          apiVersion: cluster.open-cluster-management.io/v1
          kind: ManagedCluster
          metadata:
            labels:
              local-cluster: "true"
              cloud: auto-detect
              vendor: auto-detect
            name: local-cluster
          spec:
            hubAcceptsClient: true
            leaseDurationSeconds: 60
        apply: true
        state: present
        wait: true
        wait_timeout: 600
        wait_condition:
          type: ManagedClusterConditionAvailable
          status: "True"
      register: k8s_result
      until: k8s_result is not failed

    - name: Patch MCE
      kubernetes.core.k8s:
        definition:
          apiVersion: multicluster.openshift.io/v1
          kind: MultiClusterEngine
          metadata:
            name: multiclusterengine
          spec:
            overrides:
              components:
                - enabled: true
                  name: hypershift-preview
        state: present
        wait: true
        wait_timeout: 1200
        wait_condition:
          type: Available
          status: "True"
      register: k8s_result
      until: k8s_result is not failed

- name: Install MetalLB operator # noqa role-name[path]
  ansible.builtin.include_role:
    name: "{{ playbook_dir }}/../common/roles/install_operator"
  vars:
    operator_name: metallb-operator
    operator_namespace: metallb-system
    all_namespaces: true
    cluster_monitoring: false

- name: Create MetalLB
  kubernetes.core.k8s:
    definition:
      apiVersion: metallb.io/v1beta1
      kind: MetalLB
      metadata:
        name: metallb
        namespace: metallb-system
    apply: true
    state: present
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 600
  register: k8s_result
  until: k8s_result is not failed

- name: Set up GitOps
  block:
    - name: Install GitOps operator # noqa role-name[path]
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../common/roles/install_operator"
      vars:
        operator_name: openshift-gitops-operator
        operator_namespace: openshift-operators

    - name: Create ClusterRoleBinding for GitOps
      kubernetes.core.k8s:
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: gitops-cluster-admin
          subjects:
            - kind: ServiceAccount
              name: openshift-gitops-argocd-application-controller
              namespace: openshift-gitops
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
        apply: true
        state: present
      register: k8s_result
      until: k8s_result is not failed
